title: "RAMAZANI KASIGE JACOB"
baseline: "Développeur Etudiant passionné"
description: "Développeur passionnée par la Programmation embarqué technologie."

params:
  author: "RAMAZANI KASIGE JACOB"
  github: "https://github.com/Brayrams-del"
  email: "brayrams@icloud.com"
  social:
    - name: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Brayrams-del"
    - name: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "#"
    - name: "Twitter"
      icon: "fab fa-twitter"
      url: "#"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Projets"
      url: "/projets/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Contact"
      url: "/contact/"
      weight: 4
